# Generated by Django 2.2.4 on 2019-08-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190803_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
