# Generated by Django 2.2.4 on 2019-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20190803_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='regions',
        ),
        migrations.AddField(
            model_name='region',
            name='cities',
            field=models.ManyToManyField(to='cities.City'),
        ),
    ]
